id: D9ECB811B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:52:36+00:00'
last_modified: '2022-05-26T07:51:11.964289+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a79a:
      image_group_id: I1PD95850
      title: ཀྱེའི་རྡོ་རྗེ་ལས་བྱུང་བའི་ཀུ་རུ་ཀུ་ལླེའི་མན་ངག་ཆེན་པོ་ལྔ།
      total_pages: 2069
      order: 5
      base_file: a79a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
