id: PFFBBD884
initial_creation_type: ocr
source_metadata:
  volumes:
    e1e10bfc56594a0cb0348d81dec78d8e:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: ཀྱེའི་རྡོ་རྗེ་ལས་བྱུང་བའི་ཀུ་རུ་ཀུ་ལླེའི་མན་ངག་ཆེན་པོ་ལྔ།
      total_pages: 2069
      volume_number: 5
